# Contains files that will be tar'd and installed under share
INSTALLFILES +=

# Contains files that will be cleaned
CLEANFILES +=

# Contains files that will be built when build is run
BUILDFILES +=

# TODO Add any site-specific build configuration here

# Finally, include Marla-generic configuration
include Makefile.marla
