#!/bin/bash
PATH=/bin:/usr/bin

# Description: Generate a Bash shell script

die() {
    echo $* >&2
    exit 1;
}

if [ "$#" -eq 0 ]; then
    die "At least one file must be provided";
fi;

for f in $*; do
    mkdir -p `dirname $f`
    cp $SCAFDATA/scaf.sh $f

    if [ -n "$MODELINE" ]; then
        echo >>$f
        echo "# vim: set $MODELINE :" >>$f
    fi
done;

# vim: set ts=4 sw=4 et :
