#!/bin/bash
PATH=/bin:/usr/bin

die() {
    echo $* >&2
    exit 1;
}

for f in $*; do
    mkdir -p `dirname $f`
    cp $SCAFDATA/scaf.sh $f

    if [ -n "$MODELINE" ]; then
        echo >>$f
        echo "# $MODELINE" >>$f
    fi
done;

# vim: set ts=4 sw=4 et :
