#!/bin/bash
PATH=/bin:/usr/bin

# Description: Generate C++ source and header files

die() {
	echo $* >&2
	exit 1;
}

scaffold_header_file() {
    file=$1;
    shift;

    # TODO We should support using a different file if the filename
    # doesn't look like a class name
    cp $SCAFDATA/scaf.hpp $file

    header=`basename $file | \
        sed -re 's/\.[^.]+$//' \
            -e 's/\./_/g' \
        `;
    klass=`basename $header`;
    header_define=`echo $header | \
        sed -re 's/^(.*)$/\U\1/'
        `;

    # Fill in the preprocessor lines
    sed -i \
        -e "s#@HEADER_DEFINE@#${header_define}_HEADER#g" \
        -e "s#@CLASS@#$klass#g" \
        $file;

    if [ -n "$MODELINE" ]; then
        echo >>$file
        echo "// vim: set $MODELINE :" >> $file
    fi;
}

scaffold_source_file() {
    file=$1;
    shift;

    # TODO We should support using a different file if the filename
    # doesn't look like a class name
    cp $SCAFDATA/scaf.cpp $file

    # Get the right header name
    header=`echo $file | sed -re 's/\.[^.]+$//'`;
    klass=`basename $header`
    case "$file" in
        *.cpp) header="$header.hpp" ;;
        *.cxx) header="$header.hxx" ;;
        *.c) header="$header.h" ;;
        *.C) header="$header.H" ;;
        *) die "Unknown extension: $file" ;;
    esac;

    # Add a reference to the header
    sed -i \
        -e "s#@HEADER@#$header#g" \
        -e "s#@CLASS@#$klass#g" \
        $file;

    if [ -n "$MODELINE" ]; then
        echo >>$file
        echo "// vim: set $MODELINE :" >> $file
    fi;

    # Finally, generate the header as well
    scaffold_header_file $header
}

if [ "$#" -eq 0 ]; then
    die "At least one file must be provided";
fi;

for f in $*; do
    mkdir -p `dirname $file`
    if [ -e $file ]; then
        echo "$file already exists, ignoring." >&2
    else
        case "$file" in
            *.h|*.hpp) scaffold_header_file $file ;;
            *.c|*.cpp|*.C) scaffold_source_file $file ;;
            *) scaffold_source_file $file.cpp ;;
        esac;
    fi;
done;

# vim: set ts=4 sw=4 et :
