#!/bin/bash
PATH=/bin:/usr/bin

# Description: Generate a Marla-backed site

die() {
    echo $* >&2
    exit 1;
}

realname() {
    if [ -n "$OWNER" ]; then
        echo $OWNER
    else
        # Extract a name from the passwd file
        grep "^`whoami`" /etc/passwd | cut -d: -f5
    fi;
}

generate_scaffold() {
    project=$1;
    shift;

    rsync -avzih $SCAFDATA/marla/ $project || die

    pushd $project || die
    project=`pwd`
    project=`basename $project`

    email=${EMAIL:-TODO@example.com}
    website=${WEBSITE:-http://$project}

    if [ ! -e .scafrc ] || ! grep -q 'PROJECT=' .scafrc; then
        echo "PROJECT=$project" >>.scafrc
        echo "WEBSITE=$project" >>.scafrc
    fi;

    $SCAF license LICENSE

    if [ ! -e site.config ]; then
        echo "# Ensure that this can be evaluated by shell scripts" >>site.config
        echo "SITE=`basename $file`" >>site.config
    fi;

    # Substitute any relevant args
    find -type f | xargs sed -ri \
        -e "s|@@SITE@@|$project|g" \
        -e "s/@@PROJECT@@/$project/g" \
        -e "s|@@WEBSITE@@|$website|g" \
        -e "s/@@YEAR@@/`date +%Y`/g" \
        -e "s/@@DATE@@/`date +'%a %b %d %Y'`/g" \
        -e "s:@@OWNER@@:`realname`:g" \
        -e "s|@@EMAIL@@|$email|g";

    if [ -z "$NO_GIT" ] && [ ! -e .git ]; then
        # Set up git
        git init .
        git commit -m"Initial commit" --allow-empty
        git add .

        # Commit everything for our initial commit
        git commit -m"Initial scaffold for a Marla-backed site"
        git tag scaffold
    fi;
}

files=
for arg in $*; do
    case "$arg" in
        -f|--force) FORCE=true ;;
        -*) die "Unrecognized command: $arg" ;;
        *) files="$files $arg" ;;
    esac
done;
set $files

if [ "$#" -eq 0 ]; then
    die "At least one file must be provided";
fi;

for file in $*; do
    mkdir -p `dirname $file`
    if [ -z "$FORCE" ] && [ -e $file ]; then
        echo "$file already exists, ignoring." >&2
    else
        generate_scaffold $file
    fi
done;

# vim: set ts=4 sw=4 :
