#!/bin/bash
PATH=/bin:/usr/bin

# Description: Generate a Perl library

die() {
    echo $* >&2
    exit 1;
}

realname() {
    if [ -n "$OWNER" ]; then
        echo $OWNER
    else
        # Extract a name from the passwd file
        grep "^`whoami`" /etc/passwd | cut -d: -f5
    fi;
}

generate_scaffold() {
    project=`echo $1 | sed -re 's#\.pm$##' -e 's#/#::#g'`
    shift;

    project_dashes=`echo $project | sed -re 's#::#-#g' -e 's/^(.*)$/\L\1/'`

    email=${EMAIL:-TODO@example.com}
    website=${WEBSITE:-http://www.TODO.com}

    project_upper=`echo $project | sed -re "s/^(.*)$/\U\1/" -e 's/[- ]/_/g'`;

    rsync -avzih $SCAFDATA/perllib/ $project_dashes || die

    pushd $project_dashes || die
    file=`pwd`

    if [ ! -e .scafrc ] || ! grep -q 'PROJECT=' .scafrc; then
        echo "PROJECT=$project" >>.scafrc
    fi;

    find -type f | xargs sed -ri \
        -e "s/@@PROJECT@@/$project/g" \
        -e "s#@@PROJECT_SPECNAME@@#perl-`echo $project | sed -re 's#::#-#g'`#g" \
        -e "s#@@PROJECT_MODULE_PATH@@#`echo $project | sed -re 's#::#/#g' | xargs dirname`#g" \
        -e "s/@@PROJECT_MODULE@@/`echo $project | sed -re 's#::#/#g' | xargs basename`/g" \
        -e "s/@@PROJECT_DASHES@@/$project_dashes/g" \
        -e "s/@@PROJECT_UPPER@@/$project_upper/g" \
        -e "s|@@WEBSITE@@|$website|g" \
        -e "s/@@YEAR@@/`date +%Y`/g" \
        -e "s/@@DATE@@/`date +'%a %b %d %Y'`/g" \
        -e "s:@@OWNER@@:`realname`:g" \
        -e "s|@@EMAIL@@|$email|g";

    pushd lib || die
    $SCAF perlmod $project
    popd

    if [ -e $project_dashes.spec ]; then
        rm perllib.spec
    else
        mv perllib.spec $project_dashes.spec
    fi;

    if [ -n "$MODELINE" ]; then
        for sourcefile in `find . -name '*.pl'`; do
            if ! grep -q 'vim:' $sourcefile; then
                echo >>$sourcefile
                echo "# vim: set $MODELINE :" >>$sourcefile
            fi;
        done;
    fi;

    $SCAF license LICENSE

    if [ -z "$NO_GIT" ] && [ ! -e .git ]; then
        # Set up git
        git init .
        git commit -m"Initial commit" --allow-empty
        git add .

        # Commit everything for our initial commit
        git commit -m"Initial scaffold for a Bash application project"
        git tag scaffold
    fi;
}

files=
for arg in $*; do
    case "$arg" in
        -f|--force) FORCE=true ;;
        -*) die "Unrecognized command: $arg" ;;
        *) files="$files $arg" ;;
    esac
done;
set $files

if [ "$#" -eq 0 ]; then
    die "At least one file must be provided";
fi;

for file in $*; do
    mkdir -p `dirname $file`
    if [ -z "$FORCE" ] && [ -e $file ]; then
        echo "$file already exists, ignoring." >&2
    else
        generate_scaffold $file
    fi
done;

# vim: set ts=4 sw=4 :
