#!/bin/bash
PATH=/bin:/usr/bin

# Description: Generate a Autotools-backed Qt application project

die() {
    echo $* >&2
    exit 1;
}

realname() {
    if [ -n "$OWNER" ]; then
        echo $OWNER
    else
        # Extract a name from the passwd file
        grep "^`whoami`" /etc/passwd | cut -d: -f5
    fi;
}

generate_scaffold() {
    file=$1;
    shift;

    cp -v -r $SCAFDATA/qtapp $file

    pushd $file
    echo "PROJECT=$project" >>.scafrc

    project=`basename $file`
    email=${EMAIL:-TODO@example.com}
    website=${WEBSITE:-http://www.TODO.com}

    project_obj=`echo $project | sed -re 's:^(.*)$:\u\1:'`
    project_upper=`echo $project | sed -re "s/^(.*)$/\U\1/"`;
    project_underscore=`echo $project_upper | sed -re "s/[- ]/_/g"`;

    mv -v scaf.m4 $project.m4.in
    $SCAF qtmain src/main

    find -type f | xargs sed -ri \
        -e "s/@@PROJECT@@/$project/g" \
        -e "s/@@PROJECT_OBJ@@/$project_obj/g" \
        -e "s/@@PROJECT_UPPER@@/$project_upper/g" \
        -e "s/@@PROJECT_UNDERSCORE@@/$project_underscore/g" \
        -e "s|@@WEBSITE@@|$website|g" \
        -e "s/@@YEAR@@/`date +%Y`/g" \
        -e "s:@@OWNER@@:`realname`:g" \
        -e "s|@@EMAIL@@|$email|g";

    if [ -n "$MODELINE" ]; then
        for sourcefile in `find . -name '*.cpp' -o -name '*.hpp'`; do
            echo >>$sourcefile
            echo "// vim: set $MODELINE :" >>$sourcefile
        done;
    fi;

    $SCAF license

    # Set up git
    git init .
    git add .

    # Force the addition of the m4/ directory, since it's ignored in .gitignore
    git add -f m4

    # Commit everything for our initial commit
    git commit -m"Initial scaffold for an Autotools-backed Qt project"

    # Get Autotools setup
    autoreconf -i

    popd
}

if [ "$#" -eq 0 ]; then
    die "At least one file must be provided";
fi;

for file in $*; do
    mkdir -p `dirname $file`
    if [ -e $file ]; then
        echo "$file already exists, ignoring." >&2
    else
        generate_scaffold $file
    fi
done;

# vim: set ts=4 sw=4 et :
