#!/bin/bash
PATH=/bin:/usr/bin

# Description: Generate a Autotools-backed Qt library project

die() {
    echo $* >&2
    exit 1;
}

generate_scaffold() {
    file=$1;
    shift;

    cp -v -r $SCAFDATA/qtlib $file

    project=`basename $file`
    email=${EMAIL:-TODO@example.com}
    website=${WEBSITE:-http://www.TODO.com}

    pushd $file
    echo "PROJECT=$project" >>.scafrc

    project_obj=`echo $project | sed -re 's:^(.*)$:\u\1:'`
    project_upper=`echo $project | sed -re "s/^(.*)$/\U\1/"`;

    mv -v src/scaf.cpp src/$project_obj.cpp
    mv -v include/scaf.hpp include/$project_obj.hpp

    find . -name '*.ac' -o -name '*.am' -o -name '*.cpp' -o -name '*.hpp' | xargs sed -ri \
        -e "s/@@PROJECT@@/$project/g" \
        -e "s/@@PROJECT_OBJ@@/$project_obj/g" \
        -e "s/@@PROJECT_UPPER@@/$project_upper/g" \
        -e "s|@@WEBSITE@@|$website|g" \
        -e "s|@@EMAIL@@|$email|g";

    if [ -n "$MODELINE" ]; then
        for sourcefile in `find . -name '*.cpp' -o -name '*.hpp'`; do
            echo >>$sourcefile
            echo "// vim: set $MODELINE :" >>$sourcefile
        done;
    fi;

    $SCAF license

    # Set up git
    git init .
    git add .

    # Force the addition of the m4/ directory, since it's ignored in .gitignore
    git add -f m4

    # Commit everything for our initial commit
    git commit -m"Initial scaffold for an Autotools-backed Qt library"

    # Get Autotools setup
    autoreconf -i

    popd
}

if [ "$#" -eq 0 ]; then
    die "At least one file must be provided";
fi;

for file in $*; do
    mkdir -p `dirname $file`
    if [ -e $file ]; then
        echo "$file already exists, ignoring." >&2
    else
        generate_scaffold $file
    fi
done;

# vim: set ts=4 sw=4 et :
